<?php

namespace Package\Tests\Fixture;

class SomeClassTest
{
    public function handlePasswordChange()
    {
        self::assertEquals('1', '2');
        $this->assertEquals('3', '8');
    }
}

?>

-----
<?php

namespace Package\Tests\Fixture;

class SomeClassTest
{
    public function handlePasswordChange()
    {
        self::assertEquals('1', '2');
        $this->assertEquals('3', '8');
    }
}

?>
